server:
  port: ${PORT}

spring:
  main:
    allow-bean-definition-overriding: true   # ← add this
  
  
  name : backend
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}   # ← change this
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update          # auto-creates/updates tables from entities
    show-sql: true              # prints SQL queries in console (helpful while learning)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}       # ← change this
    password: ${MAIL_PASSWORD}    # ← NOT your login password, see note below
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}         # ← Phase 4 will fill this
            client-secret: ${GOOGLE_CLIENT_SECRET}  # ← Phase 4 will fill this
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

application:
  jwt:
    secret: ${JWT_SECRET}   # 256-bit hex key
    expiration: ${JWT_EXPIRATION}    # 24 hours in milliseconds
  frontend-url: ${FRONTEND_URL}
  oauth2:
    authorized-redirect-uri: http://localhost:5173/oauth2/callback
    cookie-expire-seconds: 180